services:
  prometheus:
    image: prom/prometheus
    volumes:
      - /var/lib/prometheus:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    user: "${UID:-1007}:${GID:-1007}"
    restart: unless-stopped

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:v1.9.0
    command:
      - "--path.rootfs=/host"
    volumes:
      - "/:/host:ro,rslave"
    pid: host
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    volumes:
      - /var/lib/grafana/:/var/lib/grafana
    user: "${UID:-1007}:${GID:-1007}"
    ports:
      - '3000:3000'
    restart: unless-stopped
    depends_on:
      - prometheus

  mqtt2prometheus:
    image: ghcr.io/hikhvar/mqtt2prometheus:latest
    user: "${UID:-1007}:${GID:-1007}"
    ports:
      - '9641:9641'
    volumes:
      - "$(pwd)/mqtt2prometheus.yaml:/config.yaml:ro"
    environment:
      - MQTT2PROM_MQTT_USER=mqtt
      - MQTT2PROM_MQTT_PASSWORD=<placeholder>

